### PR TITLE
Improved test harness for BridgeFungibleToken contract

### PR DESCRIPTION
**Pull request by nfurfaro**
This is a pretty big refactor of the test harness, which introduces a `TestConfig` struct.
A TestConfig is generated from just 2 hardcoded consts; `LAYER_1_DECIMALS` & `LAYER_2_DECIMALS`.
All other testing amounts are now derived from these initial consts, where before they were calculated and converted manually making the tests very brittle.

In order to test different configurations of decimals now, there are just 2 steps:
1. modify `LAYER_1_DECIMALS` & `LAYER_2_DECIMALS` as needed in `harness.rs`.
2. modify `LAYER_1_DECIMALS` & `LAYER_2_DECIMALS` as needed in the `forc.toml` and build the contract.

Moving forward, when the SDK allows us to set config-time consts programmatically the above process can be reduced to just step 1.

### CODE REVIEW

**Comment by nfurfaro** [comment]
I jumped the gun, need to update for the new forc.

**Comment by pixelcircuits** [comment]
So one thing I notice during the integration tests is that when encoding the output message data, the function selector is getting padded out to a full word (8 bytes) instead of just 4 bytes. Your tests seem to assume that this is correct, but it's technically not what the solidity contract expects and causes a failure. The question is, should we figure out how to support data blobs that aren't rounded to the nearest word, or should we make the solidity handle the padding?

**Comment by nfurfaro** [comment]
>The question is, should we figure out how to support data blobs that aren't rounded to the nearest word, or should we make the solidity handle the padding?

I think @sezna was working on something that could help with this, but I don't know how far away it would be from being usable. A `Bytes` type with packed, unpadded `u8`s or something?

**Comment by nfurfaro** [comment]
The newly refactored harness has allowed me to easily test the BridgeFungibleToken contract in different decimal configurations:
- LAYER_1_DECIMALS == LAYER_2_DECIMALS
- LAYER_1_DECIMALS > LAYER_2_DECIMALS
- LAYER_1_DECIMALS < LAYER_2_DECIMALS

Doing so has identified some bugs in my tests, some missed edge cases and highlighted areas where the contract was lacking. 

I'd still like to improve the case where LAYER_1_DECIMALS > LAYER_2_DECIMALS (like we're planning to deploy as our first erc-20 bridge), but where ∆ decimals is very large.

Currently, we can handle a ∆ of 19; any more than that and the call to the contract from the relayer fails with an arithmetic overflow. If I'm not mistaken, this could result in lost tokens on the L1 side, as no refund is able to be registered on the fuel contract.

This could be prevented by :
- forbidding deployment of the L2 fungible token contracts with this configuration via a predicate? I'm not sure if this could work but the idea is described here: https://fuellabs.slack.com/archives/C01KBNGSWGJ/p1667651000405099
- good documentation for deploying  L2 fungible token contracts

For now I think documenting this is all we can do.

**Review by Voxelot — DISMISSED** [review]

**Review by pixelcircuits — CHANGES_REQUESTED** [review]
Need to address data encoding

**Comment by adlerjohn** [comment]
Related comment to encoding: https://github.com/FuelLabs/sway/issues/2594#issuecomment-1221205410. Having a packed `Bytes` library would do the trick, but in the absence of that then you'd have to do some manual stuff in inline asm I think on the Sway side. Or you'd have to fix on the Solidity side.

**Review by pixelcircuits — APPROVED** [review]

**Pull request merged**
